### ISSUE TITLE
Add issue using $EDITOR of your choice

### ISSUE THREAD

**Issue by rail** [mozilla/releasewarrior#10]
Adding issies via command line is nice, but sometimes you want to pass some formatting characters without worrying about shell expansions. It would be great if we can add something like `--issue --editor` which would open your editor of choice (`$EDITOR` from env?), similar to `git commit`.

**Comment by hwine** [comment]
Even better if it honors `$VISUAL`. Typical *nix convention is to pick first defined of `$VISUAL`, `$EDITOR`, hard_coded_value.

**Comment by rail** [comment]
DEAD REPO!
