### ISSUE TITLE
update troubleshooting tips

### ISSUE THREAD

**Issue by lundjordan** [mozilla/releasewarrior#115]
this should be a section for releaseduty to help troubleshoot and practice.

e.g.

nthomas> r+
17:45:06 build2 ?
17:45:56 
<•rail> I'm going to create a clone of that task, but using different revision
17:46:21 
<•nthomas> does that work with deps, or doesn't matter because this is a leaf?
17:47:31 
<•rail> yeah, IIRC that task is on the edge of the graph, nothing depends on it
17:48:13 
<•nthomas> ok, once you're done could you describe that in some detail so I can go fishing next time
17:48:29 
<•rail> sure
17:50:18 
<•nthomas> cheers
17:50:56 
<•rail> created https://tools.taskcluster.net/groups/Co8iBgS1RnKVNOWMZm0TUg/tasks/Co8iBgS1RnKVNOWMZm0TUg/details by cloning the failed task (Actions -> Edit Task) and replaced all revision entries with the new one

**Comment by kmoir** [comment]
https://github.com/mozilla/releasewarrior/commit/fd16d001f134067314553880634a399e917c1b53#diff-67212678cd3add1b394845c6374b378e
