### ISSUE TITLE
sfraser on releaseduty soon, needs write access 

### ISSUE THREAD

**Issue by srfraser** [mozilla/releasewarrior#116]
May I get access to this repo, please?

**Comment by MihaiTabara** [comment]
@lundjordan can you please take care of this? I think you're the only one with admin rights on this repo. Might be worth adding some more of us to busfactor++

**Comment by lundjordan** [comment]
A few things here. I don't believe I have admin rights. It looks like this repo is under the mozilla org with [writes and access](https://github.com/orgs/mozilla/teams/releng/repositories) allocated to the "releng" team within the org. Interestingly, it seems Simon is [not in the releng team](https://github.com/orgs/mozilla/teams/releng/members).

So I think we have a few action items:

1) add sfraser to the "releng" team under Mozilla org
2) remove coop and add a third [maintainer](https://github.com/orgs/mozilla/teams/releng/members?utf8=%E2%9C%93&query=%20role%3Amaintainer) to the "releng" team
3) move releasewarrior under the preferred mozilla-releng org

I'll get an issue started for (3). Perhaps @catlee can help with (1) and (2)

**Comment by lundjordan** [comment]
tracking move to mozilla-releng here: #118

**Comment by catlee** [comment]
I can't add anybody to the releng team who's not part of the mozilla org.
jlund, you are also not a member of the releng team here!

In the meanwhile I've added rail as a maintainer, and set coop as a normal
member.

**Comment by srfraser** [comment]
Fixed for my case, the other issue tracks the repo migration.
