### ISSUE TITLE
releasewarrior should work regardless of my cwd

### ISSUE THREAD

**Issue by bhearsum** [mozilla/releasewarrior#13]
I was surprised to find that releasewarrior threw an exception when I wasn't in the releasewarrior directory. This might be related to #2 in that it's somewhat caused by the tool and the data it manages being so closely tied together.

One way to fix this could be to _require_ a local config (perhaps one that could be generated automatically) that points at the data.

**Comment by lundjordan** [comment]
sorry, I must not have notifications setup correctly for repos that I guess I 'own' and want to see all PRs coming in :)

anyway, @mozbhearsum  does this clear things up for you? https://github.com/mozilla/releasewarrior/blob/master/releasewarrior/config.py#L4

I had it so `release` would work from any dir without any configuration via this hack: https://github.com/mozilla/releasewarrior/commit/a98ff98ad5dcdadabf3387fc4bbd4c6356682e70

but then I got complaints by people who wanted to have their venv in special ways that broke that logic.

**Comment by bhearsum** [comment]
In a world where we have the data living in the same repo as the code, I get it, yeah. I don't have any better ideas that don't involve the data living elsewhere.
