### ISSUE TITLE
Signoff requirements for shipping don't match reality?

### ISSUE THREAD

**Issue by bhearsum** [mozilla/releasewarrior#58]
Reading over https://github.com/mozilla/releasewarrior/blob/master/how-tos/relpro.md#when-2, I was surprised to see that QE is able to authorize shipping non-Betas. Is that actually true? I thought they could only authorize shipping non-beta1 betas.

**Comment by lundjordan** [comment]
good catch. I don't think these docs represent the actual policy per release-drivers requests. It needs to be scanned and sanity checked. I've added this to postmortem discussion

**Comment by rail** [comment]
Probably just a copy/paste. Our current policy:

Betas: QE or Relman
RC to Beta: QE or Relman
Everything else: Relman

**Comment by bhearsum** [comment]
I don't think that's quite right - AFAICT, Beta 1 requires Relman signoff explicitly.

**Comment by rail** [comment]
Oh, right

**Comment by kmoir** [comment]
This was changed to only relman and releng for Betas and releases in Balrog as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1392871

I'll update the releasewarrior doc to reflect current signoff rules

**Comment by kmoir** [comment]
https://github.com/mozilla/releasewarrior/commit/d5b30406561ec59e9a8c79e9ffc4c4e9177ae334

Updated it here
