### ISSUE TITLE
maybe put a `whoami` in front of issues automatically?

### ISSUE THREAD

**Issue by escapewindow** [mozilla/releasewarrior#79]
to make it easier to see who added them

**Comment by MihaiTabara** [comment]
We need to update the postmortem logic to encompass these as well. For some reason it currently doesn't work.

**Comment by escapewindow** [comment]
Look at the raw content: https://raw.githubusercontent.com/mozilla/releasewarrior/master/releases/POSTMORTEMS/2017-06-07.md

It's there. < and > are special characters in html that mark entities, which don't show on the page.  I'm guessing that's why they're not showing.

**Comment by MihaiTabara** [comment]
Ah, sweet. I was debugging in command line. Thanks for the heads-up!
